spring.application.name=distributed-booking
# Render sẽ tự cấp Port, dòng này giúp Spring nhận Port từ Render hoặc mặc định 8080 ở máy nhà
server.port=${PORT:8080}

# Cấu hình linh hoạt: Ưu tiên lấy từ biến môi trường (Environment Variables)
server.id=${SERVER_ID:Local-Server}
peer.servers=${PEER_SERVERS:http://localhost:8081,http://localhost:8082}

# Tắt cache Thymeleaf để dev cho nhanh
spring.thymeleaf.cache=false

# Kết nối MongoDB Atlas (Giữ nguyên link của Dương)
spring.data.mongodb.uri=mongodb+srv://dluu5032_db_user:Mvt7lR6jK0INhlo6@cluster0.rw2nn1s.mongodb.net/FlightDB?retryWrites=true&w=majority